version: "3.6"

services:
    openvpn:
        container_name: openvpn
        image: kylemanna/openvpn:2.3
        volumes:
            - .:/local
            - ./config:/etc/openvpn
        network_mode: host
        cap_add:
            - NET_ADMIN
        environment:
            dest: docker-for-mac.ovpn
            DEBUG: "1"
        command: /local/helpers/run.sh
        restart: always

    openvpn-proxy:
        container_name: openvpn-proxy
        image: alpine/socat:1.0.2
        ports:
            - "127.0.0.1:13194:13194"
        command: TCP-LISTEN:13194,fork TCP:172.17.0.1:1194
        restart: always
        depends_on:
            - openvpn

networks:
    default:
        driver: bridge
        name: docker-for-mac-openvpn